import tkinter as tk
window = tk.Tk()
frame_1 = tk.Frame(master=window,relief=tk.RAISED, borderwidth=5, width=500, height=500)
title = tk.Label(master=frame_1,text="UIC Search Engine")
title.place(x=150,y=30)
#title.pack()
user_input = tk.Entry(master = frame_1)
user_input.place(x=100,y=70)
#user_input.pack()
user_query = user_input.get()
button = tk.Button( master = frame_1, text="Search")
button.place(x=300,y=70)
#button.pack()
display_result = tk.Entry(master = frame_1)
display_result.insert(0,user_query)
display_result.place(x=0,y=100)
#display_result.pack()

frame_1.pack(fill=tk.BOTH, side=tk.LEFT, expand=True)
window.mainloop()